apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: yc-registry-secret
      containers:
      - name: app-v1
        image: cr.yandex/crpfsj6kk1tn7isut41s/alex_nginx:1.30.4
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend
  ports:
    - name: app-v1
      protocol: TCP
      port: 80
      targetPort: 80
